# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61ef0e699a0386b0b84eb8dbbb9cc2c96e4938d48717ccb40dbe8be945304fad60ad403b1bbb8346d1d606d069c463109adad645191bb3bf96f5480ef913ed00

test:
  secret_key_base: 1b0d6c2d1b7b976630774e21349dad6b5d6aa74a03b468fe227ed3a1ef6c12de795452f28af94d331b1f6cc1413e740918f5e9e625fe777535077edab1354c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
